src/Entity/Clip.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FileRepository")
 * @ORM\Table(name="files")
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="type", type="string")
 * @ORM\DiscriminatorMap({"file" = "App\Entity\File", "clip" = "App\Entity\Clip"})
 */
class Clip extends File
{
}

src/Form/DataTransformer/NestedCollectionToStringTransformer.php
<?php
namespace App\Form\DataTransformer;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Form\DataTransformerInterface;
use Symfony\Component\Form\Exception\TransformationFailedException;

class NestedCollectionToStringTransformer implements DataTransformerInterface
{
    /** @var string */
    private $delimiter;

    public function __construct(string $delimiter)
    {
        $this->delimiter = $delimiter;
    }

    /**
     * {@inheritdoc}
     */
    public function transform($values): string
    {
        if (!($values instanceof Collection)) {
            throw new TransformationFailedException(
                sprintf(
                    'Expected "%s", but got "%s"',
                    Collection::class,
                    is_object($values) ? get_class($values) : gettype($values)
                )
            );
        }

        if ($values->isEmpty()) {
            return '';
        }

        return implode($this->delimiter, $values->toArray());
    }

    /**
     * {@inheritdoc}
     */
    public function reverseTransform($value): Collection
    {
        if (!is_string($value)) {
            throw new TransformationFailedException(
                sprintf(
                    'Expected string, but got "%s"',
                    is_object($value) ? get_class($value) : gettype($value)
                )
            );
        }

        if ('' === $value) {
            return new ArrayCollection();
        }

        return new ArrayCollection(explode($this->delimiter, $value) ?: []);
    }
}

src/Form/Type/ClipType.php
<?php

namespace App\Form\Type;

use Sylius\Bundle\ResourceBundle\Form\Type\AbstractResourceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Sylius\Bundle\ResourceBundle\Form\Type\ResourceAutocompleteChoiceType;

class ClipType extends AbstractResourceType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class)
            ->add('files', MediaChoiceType::class, [
                'multiple' => true,
                'resource' => 'app.file',
                'choice_name'=> 'name',
                'choice_value' => 'id',
            ])
        ;
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'app_clip';
    }
}

src/Form/Type/Filter/FileFilterType.php
<?php

namespace App\Form\Type\Filter;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FileFilterType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add(
            'type',
            ChoiceType::class,
            ['choices' => ['fle', 'clip']]
        );
    }
}

src/Form/Type/MediaChoiceType.php
<?php

declare(strict_types=1);

namespace App\Form\Type;

use Sylius\Bundle\ResourceBundle\Form\Type\ResourceAutocompleteChoiceType;
use Symfony\Component\Form\AbstractType;


use Sylius\Bundle\ResourceBundle\Form\DataTransformer\CollectionToStringTransformer;
use Sylius\Bundle\ResourceBundle\Form\DataTransformer\RecursiveTransformer;
use Sylius\Bundle\ResourceBundle\Form\DataTransformer\ResourceToIdentifierTransformer;
use Sylius\Component\Registry\ServiceRegistryInterface;
//use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\Options;
use Symfony\Component\OptionsResolver\OptionsResolver;


class MediaChoiceType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        if (!$options['multiple']) {
            $builder->addModelTransformer(
                new ResourceToIdentifierTransformer(
                    $options['repository'],
                    $options['choice_value']
                )
            );
        }

        if ($options['multiple']) {
            $builder
            ->addModelTransformer(new \Symfony\Component\Form\CallbackTransformer(
                function ($values) {

                    $values = $values->map(function ($value) {
                        return $value->getFile();
                    });

                    return $values;
                },
                function ($values) {
                    $ord = 0;
                    $values = $values->map(function ($value) use (&$ord) {
                        ++$ord;
                        $clipFile = new \App\Entity\ClipFile;
                        $clipFile->setFile($value);
                        $clipFile->setOrd($ord);
                        return $clipFile;
                    });

                    return $values;
                }
            ))
            ;
        }
    }


    /**
     * {@inheritdoc}
     */
    public function getParent(): string
    {
        return ResourceAutocompleteChoiceType::class;
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix(): string
    {
        return 'media_choice';
    }
}

templates/clip/form/custom_types.html.twig
{% block media_choice_row %}
    {{ form_label(form) }}
    {{ form_widget(form) }}
    {{ form_help(form) }}
    {{ form_errors(form) }}

    <div class="row">
        <div class="col-7">

            <h4>Selected <span id="playlistDuration" class="badge badge-pill badge-primary">00:00:00</span></h4>

            <ul id="playlist" class="list-group">
                {% for file in form.parent.vars.data.files %}
                {% set file = file.file %}
                    <li data-id="{{ file.id }}" data-duration="{{ (file.duration / 100) |round(0, 'ceil') }}" class="ui-state-default text-truncate list-group-item">
                        {{ file.name }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <ul>
                            {% for subfile in file.files %}
                            {% set subfile = subfile.file %}
                            <li data-duration="{{ (subfile.duration / 100) |round(0, 'ceil') }}">{{subfile.name }}</li>
                            {% endfor %}
                        </ul>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="col-5">
            <h3>Media</h3>

            <div class="row">
                <div class="col-xl-7 col-lg-6 col-md-6 col-sm-5">
                    <input class="form-control d-inline-flex" type="text" id="media-search" placeholder="Search the media" aria-label="Search">
                </div>
                <div class="col">
                    <div class="btn-group d-inline-flex float-right" role="group" id="media-type">
                        <button type="button" class="btn btn-secondary active" data-value="">All</button>
                        <button type="button" class="btn btn-secondary" data-value="clip">Clips</button>
                        {#<button type="button" class="btn btn-secondary" data-value="file">Files</button>#}
                    </div>
                </div>
            </div>

            <ul id="catalog" class="list-group mt-2 mb-2">
            </ul>

            <nav>
              <ul id="catalog-paginator" class="pagination">
              </ul>
            </nav>

        </div>
    </div>

<style type="text/css">
    ul#catalog, ul#playlist { list-style-type: none; margin: 0; padding: 0; }

    #tabs-1 button.close { float: right; }
    #tabs-1 button:hover.close { cursor: pointer; }

    #playlist {background-color: #eee; border: 2px dashed #aaa; border-radius: 10px; min-height: 440px; margin-bottom: 20px; }
</style>

{% endblock %}